import type { Board, User } from "./types"

export const users: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@cengineers.com",
    role: "manager",
    status: "active",
    lastActive: "Just now",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane.smith@cengineers.com",
    role: "engineer",
    status: "active",
    lastActive: "5 minutes ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-3",
    name: "Alex Johnson",
    email: "alex.johnson@cengineers.com",
    role: "designer",
    status: "active",
    lastActive: "1 hour ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-4",
    name: "Sarah Williams",
    email: "sarah.williams@cengineers.com",
    role: "researcher",
    status: "inactive",
    lastActive: "2 days ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-5",
    name: "Michael Brown",
    email: "michael.brown@cengineers.com",
    role: "engineer",
    status: "active",
    lastActive: "3 hours ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const initialBoardData: Board = {
  id: "board-1",
  title: "Main Board",
  columns: [
    {
      id: "column-1",
      title: "To Do",
      tickets: [
        {
          id: "ticket-1",
          title: "Implement user authentication",
          description: "Set up user authentication using NextAuth.js with email/password and Google OAuth options.",
          type: "feature",
          priority: "high",
          dueDate: "2023-12-15",
          assignee: users[1],
          comments: [],
          attachments: [],
          createdAt: "2023-12-01T10:00:00Z",
          updatedAt: "2023-12-01T10:00:00Z",
        },
        {
          id: "ticket-2",
          title: "Design landing page mockups",
          description: "Create mockups for the new landing page focusing on conversion and user engagement.",
          type: "task",
          priority: "medium",
          dueDate: "2023-12-10",
          assignee: users[2],
          comments: [],
          attachments: [],
          createdAt: "2023-12-02T09:30:00Z",
          updatedAt: "2023-12-02T09:30:00Z",
        },
        {
          id: "ticket-3",
          title: "Research AI integration options",
          description:
            "Conduct research on available AI APIs and libraries that could be integrated for the assignee suggestion feature.",
          type: "research",
          priority: "low",
          dueDate: "2023-12-20",
          assignee: users[3],
          comments: [],
          attachments: [],
          createdAt: "2023-12-03T14:15:00Z",
          updatedAt: "2023-12-03T14:15:00Z",
        },
      ],
    },
    {
      id: "column-2",
      title: "In Progress",
      tickets: [
        {
          id: "ticket-4",
          title: "Fix responsive layout issues",
          description:
            "Address the layout issues on mobile devices, particularly on the dashboard and user profile pages.",
          type: "bug",
          priority: "high",
          dueDate: "2023-12-08",
          assignee: users[2],
          comments: [
            {
              user: users[0],
              text: "This is becoming a critical issue as more users access from mobile.",
              createdAt: "2023-12-04T11:30:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-04T10:00:00Z",
          updatedAt: "2023-12-04T11:30:00Z",
        },
        {
          id: "ticket-5",
          title: "Implement drag-and-drop functionality",
          description: "Add drag-and-drop functionality to the Kanban board using React DnD or a similar library.",
          type: "feature",
          priority: "medium",
          dueDate: "2023-12-12",
          assignee: users[1],
          comments: [],
          attachments: [],
          createdAt: "2023-12-05T09:00:00Z",
          updatedAt: "2023-12-05T09:00:00Z",
        },
      ],
    },
    {
      id: "column-3",
      title: "Review",
      tickets: [
        {
          id: "ticket-6",
          title: "Optimize database queries",
          description:
            "Review and optimize the current database queries to improve performance, especially for the dashboard.",
          type: "task",
          priority: "medium",
          dueDate: "2023-12-09",
          assignee: users[4],
          comments: [
            {
              user: users[1],
              text: "I've implemented the changes. Please review when you have time.",
              createdAt: "2023-12-06T15:45:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-06T13:00:00Z",
          updatedAt: "2023-12-06T15:45:00Z",
        },
      ],
    },
    {
      id: "column-4",
      title: "Done",
      tickets: [
        {
          id: "ticket-7",
          title: "Set up CI/CD pipeline",
          description: "Configure GitHub Actions for continuous integration and deployment to Vercel.",
          type: "task",
          priority: "high",
          dueDate: "2023-12-05",
          assignee: users[4],
          comments: [
            {
              user: users[0],
              text: "Great work! This will streamline our deployment process.",
              createdAt: "2023-12-05T16:30:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-04T11:00:00Z",
          updatedAt: "2023-12-05T16:30:00Z",
        },
        {
          id: "ticket-8",
          title: "Create user onboarding flow",
          description: "Design and implement the user onboarding flow to improve new user experience.",
          type: "feature",
          priority: "medium",
          dueDate: "2023-12-03",
          assignee: users[2],
          comments: [],
          attachments: [],
          createdAt: "2023-12-01T13:00:00Z",
          updatedAt: "2023-12-03T17:00:00Z",
        },
      ],
    },
  ],
}
